export { StarCanvas } from "./StarsCanvas";
export { About } from "./About";
export { Contact } from "./Contact";
export { Experience } from "./Experience";
export { Feedbacks } from "./Feedbacks";
export { Hero } from "./Hero";
export { Navbar } from "./Navbar";
export { Tech } from "./Tech";
export { Works } from "./Works";
